### ISSUE TITLE
[BUG] Missing supported version in badge

### ISSUE THREAD

**Issue by liayn** [eliashaeussler/typo3-badges#735]
### Browser

FF

### Operating system

-

### Current behavior

https://extensions.typo3.org/extension/rx_shariff
Allows v11 and v12

![TYPO3 versions](https://typo3-badges.dev/badge/rx_shariff/typo3/shields.svg)
only shows v11

### Expected behavior

`11 & 12` is shown in the badge

### Additional context

I don't know if this a problem of the TER API, but I since the TER itself shows it correctly...

**Comment by eliashaeussler** [comment]
Hi @liayn, since we completely rely on TER API responses, there's probably an issue over there. I was able to reproduce this for EXT:news and created an issue: https://git.typo3.org/services/t3o-sites/extensions.typo3.org/ter/-/issues/586

For EXT:rx_shariff, the information seems to be correct, AFAICS.

<img width="635" alt="image" src="https://github.com/eliashaeussler/typo3-badges/assets/16313625/4ff67939-358e-4572-90b9-47542f3f7346">

Side note: It might happen that badges are not up to date if there was a recent upload to TER. Extension metadata is cached for 60 minutes.

**Comment by liayn** [comment]
Interesting. I uploaded a new version of shariff right after creating this issue, but nothing changed in regards to compatibility here. Alright.

Feel free to close this issue, if you don't need it anymore.
